name: Changelog
on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
    branches: [main]
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"

jobs:
  get-label:
    runs-on: ubuntu-latest
    name: get label
    outputs:
      labels: "${{ steps.pr-labels.outputs.labels }}"
    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.9
        
  check-changelog-updates:
    if: "${{ needs.get-label.outputs.labels != ' skip-changelog ' }}"
    runs-on: ubuntu-latest
    needs: get-label
    name: check changelog update
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: get changed files
      id: changed-files
      uses: tj-actions/changed-files@v41

    - name: check file
      if: ${{ steps.changed-files.outputs.all_changed_files != '' }}
      run: |
        set -xv
        git diff --quiet origin/main... ./CHANGELOG.md
        if [ $? -ne 1 ]; then
          echo "Following files have been changed:"
          echo $(git diff --name-only origin/main... ./)
          echo ""
          echo "Please update the CHANGELOG.md required for this PR".
          exit 1
        fi
        set +xv
